version: 0.2

frontend:
  phases:
    install:
      runtime-versions:
        nodejs: 12

      commands:
        - npm install

    build:
      commands:
        - npm run build

  artifacts:
    files:
      - src/*
      - package.json
      - index.js
      - webpack.config.js